---
author: "Matthieu VERON"
date: "6/9/2022"
output:
    pdf_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 6
header-includes:   
-  \pagenumbering{gobble}
number_sections: yes
csl: fish-and-fisheries.csl
toc: yes
title: "A template to compile and run GMACS to compare management quantities between different versions."
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE)
main.path <- dirname(dirname(rstudioapi::getActiveDocumentContext()$path))

knitr::opts_chunk$set(root.dir = main.path)
knitr::opts_knit$set(root.dir = main.path)
```

```{r}

rm(list = ls())

# Install and load the packages----

# 1.Install devtools and gdata on your machine ----
if (!require("devtools")) {                        # install devtools
  install.packages("devtools")
}

if (!require("gdata")) {                        # needed to manipulate data
  install.packages("gdata")
}

# 2. Install / update gmr package ----
.Src <- "GMACS-project/gmr"
.Update <- 0                            # Get the latest version of gmr? (0: no; 1: install for the first time;
                                        # 2: update the package)
mylib <- "~/R/win-library/4.1"          # the library directory to remove the 
# gmr package from

#  remotes::install_github() will work to install gmr on your machine
if(.Update == 1) devtools::install_github(.Src)


# Updating to the latest version of gmr
if(.Update == 2){
  remove.packages("gmr", lib=mylib)
  devtools::install_github(.Src)
} 

# Load the gmr package
library(gmr)

```



```{r Define runs and versions, echo=F, message=FALSE, warning=FALSE, include=FALSE}

# Set the working directory
# setwd(dirname(dirname(rstudioapi::getActiveDocumentContext()$path)))


# Species of interest
.Spc <-c(
  "SMBKC"
  # "all"
  # "WAG",
  # "EAG"
  )

# Names of the GMACS version to consider for run
.GMACS_version <- c(
  "Dvpt_Version"
  # "Latest_Version"
  )

# Define directory
# /!\ If the last assessment is used here, the directory for this 
# folder will be: paste0(dirname(getwd()), "/Assessments/")

.VERSIONDIR <- c(
  paste0(getwd(), "/GMACS_versions/Dvpt_Version/")
  # paste0(getwd(), "/Latest_Version/")
)

# Use Last Assessment for comparison?
# If yes, you must provide the names of the model for each species in the variable .ASSMOD_NAMES
# Those model folder must have to be hold in the folder Assessments
.ASS <- FALSE

# names of the model for the last assessment - Only useful if comparison is made.
# if all stocks are considered they have to be ordered as follow:
# "AIGKC/EAG" / "AIGKC/WAG" / "BBRKC" / "SMBKC" / "SNOW"
.ASSMOD_NAMES <- NULL
                # c("model_21_1e",
                #   "model_21_1e",
                #   "model_21_1",
                #   "model_16_0",
                #   "model_21_g")

# Need to conpile the model?
  # vector of length(.GMACS_version)
  # 0: GMACS is not compiled. This assumes that an executable exists in the directory of the concerned version.
  # 1: GMACS is compiles
.COMPILE <- c(1)

# Run GMACS
.RUN_GMACS <- TRUE

# Use latest available data for the assessment?
.LastAssDat <- TRUE

# Define the directories for ADMB
.ADMBpaths <- "ADpaths.txt"


# Do comparison?
.MAKE_Comp <- FALSE

# Show Rterminal
.VERBOSE <- TRUE

```

```{r, echo=TRUE, results='asis'}

res <- GMACS(
  Spc = .Spc,
  GMACS_version = .GMACS_version,
  Dir = .VERSIONDIR,
  ASS = .ASS, AssMod_names = .ASSMOD_NAMES,
  compile = .COMPILE,
  run = .RUN_GMACS,
  LastAssDat = .LastAssDat,
  ADMBpaths = .ADMBpaths,
  make.comp = .MAKE_Comp,
  verbose = .VERBOSE
)

```
